import { catalog } from "@/data/catalog";
import { defaultPlacements, validateLayout } from "@/engine/spatial";
import type { Bundle, Product, ProductCategory, Requirements } from "@/lib/design-types";
export const scoreWeights = { spatial: .25, budget: .2, style: .2, compatibility: .15, water: .1, feature: .1 };
const categoryOrder: ProductCategory[] = ["toilet", "faucet", "shower", "vanity", "mirror", "accessory"];
export function validateRequirements(r: Requirements): string[] { const errors: string[] = []; if (r.room.length < 1.4 || r.room.width < 1.2 || r.room.height < 2) errors.push("Room dimensions are too small for a safe planning estimate."); if (r.minBudget < 0 || r.maxBudget <= r.minBudget) errors.push("Maximum budget must be greater than minimum budget."); if (!r.mandatory.length) errors.push("Choose at least one mandatory fixture."); return errors; }
export function scoreProduct(p: Product, r: Requirements): number { const roomArea = r.room.length * r.room.width; const footprint = p.dimensions.width * p.dimensions.depth; const spatial = Math.max(0, 1 - footprint / Math.max(1, roomArea * .25)); const budget = Math.max(0, 1 - p.price / Math.max(1, r.maxBudget)); const style = p.styles.includes(r.preferences.style) ? 1 : .45; const water = p.waterEfficiency ? p.waterEfficiency / 5 : .6; const featureHits = [r.preferences.smartFeatures && p.smart, r.preferences.maintenance && p.features.some(f => f.includes("clean")), r.preferences.storage && p.features.some(f => f.includes("storage"))].filter(Boolean).length; const feature = .5 + featureHits / 6; return Math.round(100 * (spatial * scoreWeights.spatial + budget * scoreWeights.budget + style * scoreWeights.style + 1 * scoreWeights.compatibility + water * scoreWeights.water + feature * scoreWeights.feature)); }
export function generateBundles(r: Requirements, source = catalog): Bundle[] { if (validateRequirements(r).length) return []; const required = categoryOrder.filter(c => r.mandatory.includes(c)); const variants = [0, 1, 2].map((offset) => { const products = required.map((category) => source.filter(p => p.category === category && p.dimensions.width <= r.room.length && p.dimensions.depth <= r.room.width).sort((a,b) => scoreProduct(b,r)-scoreProduct(a,r) || a.price-b.price)[offset] ?? source.filter(p => p.category === category).sort((a,b) => a.price-b.price)[0]).filter((p): p is Product => Boolean(p)); const total = products.reduce((sum,p)=>sum+p.price,0); const placements = defaultPlacements(products,r.room); const issues = validateLayout(r.room, placements, products); const feasible = products.length === required.length && total >= r.minBudget && total <= r.maxBudget && !issues.some(i=>i.type === "boundary" || i.type === "overlap"); const score = products.length ? Math.round(products.reduce((s,p)=>s+scoreProduct(p,r),0)/products.length) : 0; return { id:`bundle-${offset}`, name: offset === 0 ? `${r.preferences.style} Signature` : offset === 1 ? "Balanced Retreat" : "Essential Edit", products, total, remaining:r.maxBudget-total, score, feasible, placements, issues, explanation:[`${products.length} mandatory categories preserved`, `${score}/100 internal decision-support score`, r.preferences.waterConservation ? "Water-efficient options prioritized" : "Balanced for everyday performance"] }; }); return variants.filter((b,i,a)=>a.findIndex(x=>x.products.map(p=>p.id).join()===b.products.map(p=>p.id).join())===i); }
export function swapProduct(bundle: Bundle, replacement: Product, r: Requirements): Bundle { const products = bundle.products.map(p=>p.category===replacement.category?replacement:p); const total=products.reduce((s,p)=>s+p.price,0); const placements=bundle.placements.map(pl=>{ const old=products.find(p=>p.category===pl.kind); return old?{...pl,productId:old.id}:pl; }); const issues=validateLayout(r.room,placements,products); return {...bundle,products,total,remaining:r.maxBudget-total,score:Math.round(products.reduce((s,p)=>s+scoreProduct(p,r),0)/Math.max(1,products.length)),placements,issues,feasible:total<=r.maxBudget&&issues.length===0}; }
